import os
import re
import time
import json
import asyncio
from typing import List, Optional
from pydantic import BaseModel, Field
from dotenv import load_dotenv

load_dotenv()

# ─────────────────────────────────────────────────────────────────────────────
# Models
# ─────────────────────────────────────────────────────────────────────────────

class ValidatorInput(BaseModel):
    generated_answer: str = Field(..., description="The answer generated by the synthesizer")
    valid_document_ids: List[str] = Field(..., description="List of legitimate retrieved doc IDs")

class ValidatorOutput(BaseModel):
    is_valid: bool
    fabricated_ids_found: List[str] = Field(default_factory=list)
    clean_answer: str
    latency_ms: float = 0.0

# ─────────────────────────────────────────────────────────────────────────────
# Prompt 4 — Citation Validator
# ─────────────────────────────────────────────────────────────────────────────

CITATION_VALIDATOR_PROMPT = """<SYSTEM_PERSONA>
You are an automated Compliance Citation Auditor. You verify that every citation in a generated answer actually exists in the provided valid list.
</SYSTEM_PERSONA>

<INPUT_DATA>
Generated Answer: "{generated_answer}"
Valid Document IDs: {list_of_valid_ids}
</INPUT_DATA>

<RULES>
1. Extract every citation inside brackets (e.g., [DOC_123]) from the Generated Answer.
2. Check if the exact ID exists in the Valid Document IDs list.
3. If ANY ID is not in the list, set `is_valid` to false and list the fabricated IDs.
4. If invalid, output a `clean_answer` with the hallucinated citations removed.
</RULES>

<OUTPUT_FORMAT>
Respond ONLY with valid JSON:
{{
  "is_valid": boolean,
  "fabricated_ids_found": ["string"],
  "clean_answer": "string"
}}
</OUTPUT_FORMAT>"""


class CitationValidator:
    """
    Automated Compliance Citation Auditor.
    Validates that every citation bracket [DOC_ID] in the synthesized answer
    exists in the genuine retrieved document corpus.
    Provides ultra-fast regex parsing (<2ms) and Gemini LLM auditing.
    """

    CITATION_PATTERN = re.compile(r"\[([A-Za-z0-9_\-]+)\]")

    def __init__(self, api_key: Optional[str] = None, model_name: Optional[str] = None):
        self.api_key = api_key or os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
        self.model_name = model_name or os.getenv("VALIDATOR_MODEL", "gemini-3.8-flash")
        
        from llm_client import get_llm_client
        self._llm = get_llm_client()

    def validate_deterministic(self, generated_answer: str, valid_document_ids: List[str]) -> ValidatorOutput:
        """
        Fast deterministic citation validation (<1ms).
        Extracts all [DOC_ID] tokens, identifies hallucinations, and cleans text.
        """
        start = time.perf_counter()
        valid_set = set(valid_document_ids)
        
        matches = self.CITATION_PATTERN.findall(generated_answer)
        fabricated = []
        clean = generated_answer

        for cite in matches:
            if cite not in valid_set:
                if cite not in fabricated:
                    fabricated.append(cite)
                # Remove the fabricated citation and any redundant adjacent spacing
                clean = re.sub(rf"\[{re.escape(cite)}\]\s*", "", clean)

        clean = clean.strip()
        is_valid = len(fabricated) == 0
        latency = (time.perf_counter() - start) * 1000

        return ValidatorOutput(
            is_valid=is_valid,
            fabricated_ids_found=fabricated,
            clean_answer=clean,
            latency_ms=latency
        )

    async def validate(self, input_data: ValidatorInput, use_llm: bool = False) -> ValidatorOutput:
        """
        Validates citations in the answer. Uses deterministic regex by default for real-time latency (<2ms),
        or can invoke Gemini LLM if explicitly requested or for auditing.
        """
        # If LLM requested and available
        if use_llm and self._llm:
            start = time.perf_counter()
            prompt = CITATION_VALIDATOR_PROMPT.format(
                generated_answer=input_data.generated_answer.replace('"', '\\"'),
                list_of_valid_ids=json.dumps(input_data.valid_document_ids)
            )
            try:
                response = await self._llm.generate_content(
                    model=self.model_name,
                    contents=prompt,
                )
                text = response.text.strip()
                # Remove markdown fences if model returned them
                if text.startswith("```"):
                    lines = text.splitlines()
                    if lines[0].startswith("```"):
                        lines = lines[1:]
                    if lines and lines[-1].startswith("```"):
                        lines = lines[:-1]
                    text = "\n".join(lines).strip()

                parsed = json.loads(text)
                return ValidatorOutput(
                    is_valid=bool(parsed.get("is_valid", False)),
                    fabricated_ids_found=parsed.get("fabricated_ids_found", []),
                    clean_answer=parsed.get("clean_answer", input_data.generated_answer),
                    latency_ms=(time.perf_counter() - start) * 1000
                )
            except Exception as e:
                print(f"[CitationValidator] LLM audit failed ({e}), falling back to deterministic.")

        # Default high-performance deterministic execution
        return self.validate_deterministic(input_data.generated_answer, input_data.valid_document_ids)
